version: '2.5'
networks:
  action_network:
services:
  bot_core:
    image: rasa/rasa:2.2.8
    container_name: rasa_core
    restart: always
    networks:
      - action_network
    volumes:
      - .:/app
    command:
      - "run"
      - "--enable-api"
      - "--cors"
      - "*"
      - "--port"
      - "5005"
    links:
      - bot_actions

  bot_actions:
    image: rasa/rasa-sdk:2.2.0
    container_name: rasa_actions
    restart: always
    networks:
      - action_network
    expose: [5055]
    volumes:
      - ./actions:/app/actions

